In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆) 
import numpy as np

In [2]:
# Print the numpy version and the configuration (★☆☆)
np.__version__

'1.19.5'

In [3]:
#configuration
np.__config__.show()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [4]:
 #Create a null vector of size 10
 x = np.zeros(10)

In [5]:
# How to find the memory size of any array (★☆☆)
x.itemsize

8

In [6]:
 # How to get the documentation of the numpy add function from the command line? (★☆☆)
 import numpy; numpy.info(numpy.add)

In [7]:
#Create a null vector of size 10 but the fifth value which is 1
y = np.zeros(10)
y[5] = 1
y

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [8]:
#Create a vector with values ranging from 10 to 49 (★☆☆)
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
# Reverse a vector (first element becomes last) (★☆☆)
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [10]:
#Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
p = np.arange(9).reshape(3,3)
p

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [12]:
# Create a 3x3 identity matrix (★☆☆)
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#Create a 3x3x3 array with random values
b = np.random.random((3,3,3))
b

array([[[0.47263304, 0.24030207, 0.6236475 ],
        [0.6031523 , 0.02356308, 0.54532764],
        [0.30807184, 0.51778062, 0.99150281]],

       [[0.97603387, 0.47084745, 0.01138123],
        [0.82927025, 0.08950011, 0.46267452],
        [0.68946728, 0.39291224, 0.20995674]],

       [[0.5941712 , 0.10125602, 0.88775796],
        [0.59884009, 0.23670315, 0.30026099],
        [0.15197052, 0.11153989, 0.17169229]]])

In [14]:
#Create a 10x10 array with random values and find the minimum and maximum values
c = np.random.random((10,10))
print(c.min(),c.max())


0.013902329276277214 0.9923993881747142


In [15]:
#Create a random vector of size 30 and find the mean value (★☆☆)
d = np.random.random(30)
d.mean()

0.5810444673121872

In [16]:
# Create a 2d array with 1 on the border and 0 inside (★☆☆)
e = np.ones((10,10))
e[1:-1,1:-1] = 0
e


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
# How to add a border (filled with 0's) around an existing array? (★☆☆)
f = np.arange(1,13).reshape(4,3)
f

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
np.pad(f,pad_width = 1,mode = 'constant',constant_values=0)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  0],
       [ 0,  4,  5,  6,  0],
       [ 0,  7,  8,  9,  0],
       [ 0, 10, 11, 12,  0],
       [ 0,  0,  0,  0,  0]])

In [19]:
# What is the result of the following expression?
print(0 * np.nan,"and",np.inf > np.nan)

nan and False


In [20]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
g = np.diag(1+np.arange(4), k = -1)
g


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [21]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
h = np.zeros((8,8), dtype = int)

h[1::2, ::2 ]= 1
h[::2, 1::2] = 1
h

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [22]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
(np.unravel_index(100, (6,7,8)))

(1, 5, 4)

In [23]:
# 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
array= np.array([[0,1], [1,0]])
i = np.tile(array,(4,4))
i

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [24]:
# 22. Normalize a 5x5 random matrix (★☆☆)
j = np.random.random((5,5))
jmax, jmin = j.max(), j.min()
j= (j-jmin)/(jmax-jmin)
print (j)

[[5.72387782e-01 9.00149568e-01 1.26033708e-01 1.45440681e-01
  4.65009948e-02]
 [5.32597327e-01 3.52740470e-01 5.70785162e-01 2.58196341e-01
  7.78211605e-01]
 [1.00000000e+00 0.00000000e+00 4.88917454e-01 1.08363873e-01
  7.49792982e-02]
 [8.79069191e-01 5.22019740e-02 5.92934280e-01 3.44281919e-01
  7.38028300e-02]
 [4.04594168e-04 2.66619503e-01 8.25595584e-01 3.12531896e-01
  1.80960578e-01]]


In [25]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte, 1),('g',np.ubyte, 1 ),('b',np.ubyte,1),('a',np.ubyte,1)])
color

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [26]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
k = np.dot(np.ones((5,3)),np.ones((3,2)))
k

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [27]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place
l = np.arange(11)
l[(3 < l) & (l <= 8)] *= -1
l

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [28]:
#26. What is the output of the following script?


print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


In [29]:
# 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
m =np.arange(10)
print(m,"\n",m**m,"\n",(2 << z >> 2),"\n",(z <- z),"\n",(1j*z),"\n",(z/1/1),)

[0 1 2 3 4 5 6 7 8 9] 
 [        1         1         4        27       256      3125     46656
    823543  16777216 387420489] 
 [            512            1024            2048            4096
            8192           16384           32768           65536
          131072          262144          524288         1048576
         2097152         4194304         8388608        16777216
        33554432        67108864       134217728       268435456
       536870912      1073741824      2147483648      4294967296
      8589934592     17179869184     34359738368     68719476736
    137438953472    274877906944    549755813888   1099511627776
   2199023255552   4398046511104   8796093022208  17592186044416
  35184372088832  70368744177664 140737488355328 281474976710656] 
 [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False

In [30]:
# 29. How to round away from zero a float array ?
n = np.array([-5.5,2.3,1.4,-3.2,-5.3])
nn=np.copysign(np.ceil(np.abs(n)),n)
print(nn)




[-6.  3.  2. -4. -6.]


In [31]:
# 29. How to round away from zero a float array ?
n1 = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(n1)), n1))

[ 4.  1.  9. -9.  7. -4. -4.  8. -5. 10.]


In [32]:
# 30. How to find common values between two arrays? 
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,20,10)
print(Z1,"\n",Z2)
Z3 = np.intersect1d(Z1,Z2)
Z3

[7 4 0 8 0 8 5 6 3 7] 
 [ 9 19 14 13 14  4  2  6  7 10]


array([4, 6, 7])

In [33]:
# 32. Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [34]:
# 33. How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday,"\n",today,"\n",tomorrow,"\n")

2021-12-30 
 2021-12-31 
 2022-01-01 



In [35]:
# 34. How to get all the dates corresponding to the month of July 2016?
Z4 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z4)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [36]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)



array([-1.5, -1.5, -1.5])

In [37]:
# 36. Extract the integer part of a random array using 5 different methods
a1 = np.random.uniform(0,10,10)
print (a1 - a1%1)
print (np.floor(a1))
print (np.ceil(a1)-1)
print (a1.astype(int))
print (np.trunc(a1))



[1. 8. 9. 3. 1. 3. 8. 1. 1. 8.]
[1. 8. 9. 3. 1. 3. 8. 1. 1. 8.]
[1. 8. 9. 3. 1. 3. 8. 1. 1. 8.]
[1 8 9 3 1 3 8 1 1 8]
[1. 8. 9. 3. 1. 3. 8. 1. 1. 8.]


In [38]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
o = np.zeros((5,5))
o += np.arange(5)
print(o)



[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [39]:
#38. Consider a generator function that generates 10 integers and use it to build an array
def generate():
    for x in range(10):
        yield x
p = np.fromiter(generate(),dtype=float,count=-1)
print(p)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [40]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
q = np.linspace(0,1,11,endpoint=False)[1:]
print(q)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [41]:
# 40. Create a random vector of size 10 and sort it 
r = np.random.random(10)
r.sort()
r

array([0.11024865, 0.18617689, 0.26379269, 0.56112882, 0.57213623,
       0.65887226, 0.74557924, 0.78967028, 0.91894666, 0.94808025])

In [42]:
# 41. How to sum a small array faster than np.sum?
s = np.arange(10)
np.add.reduce(s)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# 42. Consider two random array A and B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [44]:
# 43. Make an array immutable (read-only)
t = np.zeros(10)
t.flags.writeable = False
t[0] = 1

ValueError: ignored

In [45]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
u = np.random.random((10,2))
X,Y = u[:,0], u[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.7929352  0.8861612  0.94855274 0.89789959 0.68074108 0.80917018
 0.92194349 0.55468665 0.72777832 0.85673495]
[0.55331724 0.13503276 1.2502529  1.30523524 0.66329706 0.52627187
 0.22104809 0.92339315 1.51480781 1.34746388]


In [46]:
# 45. Create random vector of size 10 and replace the maximum value by 0
v = np.random.random(10)
v[v.argmax()] = 0
print(v)

[0.         0.05154524 0.15558284 0.07338203 0.67810527 0.8740182
 0.49811425 0.09603046 0.39344287 0.09523195]


In [47]:
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
w = np.zeros((5,5), [('x',float),('y',float)])
w['x'], w['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(w)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [48]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [49]:
# 48. Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [50]:
# 49. How to print all the values of an array?
Z = np.arange(100).reshape(20,5)
np.set_printoptions()




In [51]:
# 50. How to find the closest value (to a given scalar) in a vector?
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

99


In [52]:
# 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [53]:
# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)




[[0.         0.97135834 0.71066081 0.70633358 0.77248256 0.65852398
  0.29616049 0.62819226 0.96456871 0.87004991]
 [0.97135834 0.         0.36517312 0.43284718 0.27923005 0.5436179
  0.68023661 0.35360713 0.66400156 0.144483  ]
 [0.71066081 0.36517312 0.         0.07600693 0.08679219 0.18115826
  0.46494324 0.15670209 0.83981874 0.22202593]
 [0.70633358 0.43284718 0.07600693 0.         0.15456359 0.11107494
  0.48422603 0.21811622 0.91165744 0.28840275]
 [0.77248256 0.27923005 0.08679219 0.15456359 0.         0.26468521
  0.50959912 0.16587145 0.79532274 0.13543707]
 [0.65852398 0.5436179  0.18115826 0.11107494 0.26468521 0.
  0.47695113 0.29111813 0.98980952 0.39926095]
 [0.29616049 0.68023661 0.46494324 0.48422603 0.50959912 0.47695113
  0.         0.35083601 0.72788398 0.58950914]
 [0.62819226 0.35360713 0.15670209 0.21811622 0.16587145 0.29111813
  0.35083601 0.         0.69922368 0.24186696]
 [0.96456871 0.66400156 0.83981874 0.91165744 0.79532274 0.98980952
  0.72788398 0.699223

In [54]:
# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [55]:
#54. How to read the following file? (★★☆)
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [56]:
# 55. What is the equivalent of enumerate for numpy arrays? 
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [57]:
# 56. Generate a generic 2D Gaussian-like array 
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [58]:
# 57. How to randomly place p elements in a 2D array?
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [59]:
# 58. Subtract the mean of each row of a matrix
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.15410729  0.02654275 -0.24435117  0.31084908 -0.24198581 -0.13407329
  -0.03428049 -0.20228194  0.3413528   0.02412078]
 [-0.27268838  0.1938922   0.01368111  0.1433532   0.12469896 -0.0030666
  -0.12533563  0.31000447 -0.00904137 -0.37549796]
 [-0.22051638  0.16079749  0.23510422  0.2689225  -0.05802268 -0.50119718
  -0.03876265 -0.15484072  0.37322694 -0.06471152]
 [ 0.50639365 -0.38309286  0.4353365  -0.02047984 -0.34368427  0.05299218
  -0.18029762 -0.0687458   0.34758087 -0.34600281]
 [ 0.25381539 -0.06203471 -0.24147602 -0.00966936  0.27388829 -0.07238431
  -0.27850071  0.40103546  0.15955143 -0.42422546]]


In [60]:
# 59. How to I sort an array by the nth column? (★★☆)


Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 8 6]
 [9 1 4]
 [4 1 9]]
[[9 1 4]
 [4 1 9]
 [1 8 6]]


In [61]:
# 60. How to tell if a given 2D array has null columns? 


Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [62]:
# 61. Find the nearest value from a given value in an array 
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4723873200111187


In [63]:
# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [64]:
# 63. Create an array class that has a name attribute
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [65]:
# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)


Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
np.add.at(Z, I, 1)
print(Z)

[2. 1. 4. 6. 3. 4. 3. 5. 1. 1.]
[ 3.  1.  7. 11.  5.  7.  5.  9.  1.  1.]


In [66]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [67]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)


w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [68]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once?
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[67 53 72 47]
 [42 43 57 51]
 [42 45 60 53]]
[[67 53 72 47]
 [42 43 57 51]
 [42 45 60 53]]


In [69]:
# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)


D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.46786013 0.37992492 0.3938882  0.43721845 0.29176308 0.50292819
 0.42180988 0.4777287  0.46125435 0.53297041]
0    0.467860
1    0.379925
2    0.393888
3    0.437218
4    0.291763
5    0.502928
6    0.421810
7    0.477729
8    0.461254
9    0.532970
dtype: float64


In [70]:
# 69. How to get the diagonal of a dot product? 

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))


array([1.75619877, 1.10879924, 1.11720042, 1.31870756, 1.48955752])

In [71]:
# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [72]:
# 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [73]:
# 72. How to swap two rows of an array? (★★★)

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [74]:
# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 41) ( 0, 97) ( 1, 63) ( 1, 65) ( 2, 54) ( 2, 64) ( 3, 73) ( 3, 77)
 ( 7, 22) ( 7, 34) (19, 41) (19, 70) (22, 34) (25, 89) (25, 92) (26, 45)
 (26, 54) (29, 36) (29, 56) (36, 56) (38, 60) (38, 67) (41, 70) (41, 97)
 (45, 54) (54, 64) (60, 67) (63, 65) (73, 77) (89, 92)]


In [75]:
# 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [76]:
# 75. How to compute averages using a sliding window over an array? (★★★)

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [77]:
# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [78]:
# 77. How to negate a boolean, or to change the sign of a float inplace?
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.56188905, -0.68736786,  0.81353779, -0.55777527,  0.23065797,
       -0.18062175,  0.38016282,  0.28029288,  0.09494858,  0.68667652,
       -0.43361021,  0.62505658,  0.56315218, -0.87854016,  0.72122466,
       -0.98802927,  0.8464371 , -0.53102241, -0.878606  ,  0.01476103,
        0.82117037,  0.13327836,  0.48361797,  0.90628577, -0.36671828,
       -0.18825797,  0.70955628, -0.15153865,  0.94397015, -0.69860057,
       -0.9438556 ,  0.76099989,  0.25919879, -0.27821785,  0.86726699,
       -0.04588027, -0.96958615,  0.03393526,  0.11022593,  0.42938958,
       -0.82786801,  0.02643105,  0.5839754 ,  0.46352308,  0.43299423,
        0.09823966,  0.42709278,  0.19480577, -0.86905087, -0.46263829,
        0.16772835,  0.03396143, -0.81071221,  0.56067876, -0.6173897 ,
       -0.475107  ,  0.53996237,  0.6668723 , -0.7036321 , -0.61904089,
        0.20379831, -0.25975161,  0.52064467, -0.71988974, -0.92814089,
        0.39292378,  0.53112554, -0.32805562, -0.38165932, -0.31

In [79]:
# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 5.25483826  3.69775283  4.79498284  6.18746457  6.84376704 12.12470014
  4.55746891  1.2931469   5.50942191 12.66575912]


In [80]:
# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.50605901  1.77138789  0.69945829  5.2433223   2.73626164  1.68270867
   6.42374193  4.99472975  2.59283279  7.09983107]
 [ 4.76086061 10.72887427  3.94658564  3.21476332  6.05861289  5.17835488
   9.01010051  0.43365664 11.77410654  1.25687024]
 [ 0.95442489  5.19580604  1.34992595  2.55798956  0.41782128  6.43389837
   4.47205122  0.2988735   6.51192236  4.54087998]
 [12.69387384  7.03686699 11.8805314  15.05421544 11.95186219  7.55046226
   4.13206624  1.56287686  5.32065911 17.04979558]
 [ 1.28189679 10.18581968  0.41287028  1.78083159  5.17560334 10.70478013
   3.91209056  5.51275972 11.9049784   0.31815871]
 [ 2.7224044   2.65400589  4.50973462  3.33659238  1.46206702  4.65912599
  12.43603943 10.76143777  2.69644003  5.03152392]
 [ 2.22260153  1.6976388   0.24805287  8.01051717  5.94923502  2.83832413
   8.14937765 10.08204453  1.34231977  9.74649183]
 [ 3.35898925  8.02124479  3.19019974  0.80447077  3.45572575  3.20982659
   9.01351368  2.06662806  8.88958217  1.09937786]


In [81]:
# 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 1 1 4 8 6 9 7 1 9]
 [2 7 4 1 2 3 6 7 9 9]
 [8 9 4 5 5 3 5 2 2 7]
 [5 4 3 0 9 1 9 8 7 3]
 [8 2 9 8 5 0 2 3 3 9]
 [6 8 5 7 0 9 1 7 1 3]
 [8 9 1 8 9 9 1 9 2 9]
 [3 5 1 5 1 2 7 1 3 5]
 [2 0 9 1 8 2 4 1 2 6]
 [9 4 0 0 3 1 8 3 5 4]]
[[0 0 0 0 0]
 [0 8 1 1 4]
 [0 2 7 4 1]
 [0 8 9 4 5]
 [0 5 4 3 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [82]:
# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [83]:
# 82. Compute a matrix rank
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [84]:
# 83. How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7


In [85]:
# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 2 3]
   [3 0 3]
   [1 4 3]]

  [[2 3 1]
   [0 3 4]
   [4 3 2]]

  [[3 1 2]
   [3 4 4]
   [3 2 4]]

  [[1 2 0]
   [4 4 0]
   [2 4 4]]

  [[2 0 3]
   [4 0 3]
   [4 4 2]]

  [[0 3 2]
   [0 3 0]
   [4 2 2]]

  [[3 2 3]
   [3 0 4]
   [2 2 2]]

  [[2 3 2]
   [0 4 3]
   [2 2 2]]]


 [[[3 0 3]
   [1 4 3]
   [4 0 4]]

  [[0 3 4]
   [4 3 2]
   [0 4 1]]

  [[3 4 4]
   [3 2 4]
   [4 1 0]]

  [[4 4 0]
   [2 4 4]
   [1 0 2]]

  [[4 0 3]
   [4 4 2]
   [0 2 4]]

  [[0 3 0]
   [4 2 2]
   [2 4 4]]

  [[3 0 4]
   [2 2 2]
   [4 4 0]]

  [[0 4 3]
   [2 2 2]
   [4 0 4]]]


 [[[1 4 3]
   [4 0 4]
   [2 2 0]]

  [[4 3 2]
   [0 4 1]
   [2 0 3]]

  [[3 2 4]
   [4 1 0]
   [0 3 2]]

  [[2 4 4]
   [1 0 2]
   [3 2 2]]

  [[4 4 2]
   [0 2 4]
   [2 2 3]]

  [[4 2 2]
   [2 4 4]
   [2 3 0]]

  [[2 2 2]
   [4 4 0]
   [3 0 3]]

  [[2 2 2]
   [4 0 4]
   [0 3 2]]]


 [[[4 0 4]
   [2 2 0]
   [2 1 4]]

  [[0 4 1]
   [2 0 3]
   [1 4 3]]

  [[4 1 0]
   [0 3 2]
   [4 3 2]]

  [[1 0 2]
   [3 2 2]
   [3 2 4]]

  [[0 2 4]
   

In [86]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3 14  3 11 12]
 [14  8  8  4 10]
 [ 3  8  1 42  8]
 [11  4 42  6 13]
 [12 10  8 13  0]]


In [87]:
# 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) 
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [88]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [89]:
# 88. How to implement the Game of Life using numpy arrays?
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [90]:
# 89. How to get the n largest values of an array
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])



[9995 9996 9997 9998 9999]


In [91]:
# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [92]:
# 91. How to create a record array from a regular array?
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [93]:
# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods
x = np.random.rand(5**7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

100 loops, best of 5: 5.37 ms per loop
10000 loops, best of 5: 171 µs per loop
10000 loops, best of 5: 165 µs per loop


In [94]:
# 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[3 4 5 6 7]


In [95]:
# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 3 1]
 [2 3 1]
 [1 1 1]
 [4 3 3]
 [3 0 0]
 [1 4 3]
 [3 4 4]
 [2 3 1]
 [3 3 3]
 [4 0 4]]
[[4 3 1]
 [2 3 1]
 [4 3 3]
 [3 0 0]
 [1 4 3]
 [3 4 4]
 [2 3 1]
 [4 0 4]]
[[4 3 1]
 [2 3 1]
 [4 3 3]
 [3 0 0]
 [1 4 3]
 [3 4 4]
 [2 3 1]
 [4 0 4]]


In [96]:
# 95. Convert a vector of ints into a matrix binary representation
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [97]:
# 96. Given a two dimensional array, how to extract unique rows?
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


In [98]:
# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)


A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.14733787, 0.17242243, 0.06209796, 0.07794905, 0.27235775,
        0.12937198, 0.2778402 , 0.27860089, 0.14296437, 0.0029591 ],
       [0.19954265, 0.23351517, 0.08410052, 0.10556797, 0.36885959,
        0.17521108, 0.37628459, 0.37731481, 0.19361953, 0.00400756],
       [0.34838815, 0.40770191, 0.1468339 , 0.18431464, 0.64400424,
        0.30590686, 0.65696779, 0.65876649, 0.33804679, 0.00699694],
       [0.16691155, 0.19532856, 0.07034761, 0.0883045 , 0.30854018,
        0.14655891, 0.31475098, 0.31561272, 0.16195703, 0.00335221],
       [0.27328901, 0.319817  , 0.11518213, 0.14458346, 0.5051816 ,
        0.23996506, 0.51535071, 0.51676167, 0.26517685, 0.00548867],
       [0.26568162, 0.31091444, 0.11197588, 0.14055878, 0.49111915,
        0.23328529, 0.50100519, 0.50237688, 0.25779528, 0.00533588],
       [0.36609353, 0.42842167, 0.15429612, 0.19368167, 0.67673308,
        0.3214533 , 0.69035546, 0.69224556, 0.35522661, 0.00735253],
       [0.08800336, 0.1029861 , 0.0370904

In [99]:
# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [100]:
# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)


X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [101]:
# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)


X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.0068435   0.34445453]
